.TH "astar_goal_visitor< Vertex >" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
astar_goal_visitor< Vertex >
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:default_astar_visitor\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBastar_goal_visitor\fP (Vertex goal)"
.br
.ti -1c
.RI "template<class Graph > void \fBexamine_vertex\fP (Vertex u, Graph &g)"
.br
.ti -1c
.RI "template<class Graph > void \fBfinish_vertex\fP (Vertex u, Graph &g)"
.br
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "template<class Vertex > \fBastar_goal_visitor\fP< Vertex >::\fBastar_goal_visitor\fP (Vertex goal)\fC [inline]\fP"

.SH "Методы"
.PP 
.SS "template<class Vertex > template<class Graph > void \fBastar_goal_visitor\fP< Vertex >::examine_vertex (Vertex u, Graph & g)\fC [inline]\fP"

.SS "template<class Vertex > template<class Graph > void \fBastar_goal_visitor\fP< Vertex >::finish_vertex (Vertex u, Graph & g)\fC [inline]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
