.TH "barrier.h" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
barrier.h
.SH SYNOPSIS
.br
.PP
\fC#include 'point\&.h'\fP
.br
\fC#include 'mygraph\&.h'\fP
.br
\fC#include 'gamemap\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBIBarrier\fP"
.br
.RI "Интерфейс препятствия "
.ti -1c
.RI "class \fBBarrier\fP"
.br
.RI "Базовый класс препятствия "
.ti -1c
.RI "class \fBBQuadrAngle\fP"
.br
.RI "Класс прямоугольного препятствия "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
