.TH "Barrier" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Barrier \- Базовый класс препятствия  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <barrier\&.h>\fP
.PP
Базовые классы:\fBIBarrier\fP и \fBPoint\fP\&.
.PP
Производные классы:\fBBQuadrAngle\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBBarrier\fP ()"
.br
.RI "Конструктор по умолчанию "
.ti -1c
.RI "\fBBarrier\fP (float \fBx\fP, float \fBy\fP)"
.br
.RI "Конструктор с параметрами "
.ti -1c
.RI "\fBBarrier\fP (const \fBBarrier\fP &o)"
.br
.RI "Конструктор копирования "
.ti -1c
.RI "\fB~Barrier\fP ()"
.br
.RI "Деструктор "
.ti -1c
.RI "int \fBinit\fP (\fBMyGraph\fP &graph, float step, \fBGameMap\fP &g) override"
.br
.RI "Инициализация препятсвия на графе "
.ti -1c
.RI "void \fBprint\fP (\fBGameMap\fP &g) override"
.br
.RI "Печать препятствия в консоль "
.ti -1c
.RI "bool \fBhasPoint\fP (\fBPoint\fP p, \fBGameMap\fP &g) override"
.br
.RI "Принадлежит ли точка пространства препятствию "
.ti -1c
.RI "bool \fBhasVertex\fP (int v, \fBGameMap\fP &g) override"
.br
.RI "Принадлежит ли вершина графа препятствию "
.ti -1c
.RI "void \fBprintToFile\fP (ofstream &out) override"
.br
.RI "Печать препятствия в файл "
.ti -1c
.RI "bool \fBisIntersection\fP (\fBPoint\fP a, \fBPoint\fP b) override"
.br
.RI "Проверка на пересечение отрезка и препятствия "
.in -1c
.SS "Друзья"

.in +1c
.ti -1c
.RI "ofstream & \fBoperator<<\fP (ofstream &out, const \fBBarrier\fP &barrier)"
.br
.in -1c
.SS "Дополнительные унаследованные члены"
.SH "Подробное описание"
.PP 
Базовый класс препятствия 
.SH "Конструктор(ы)"
.PP 
.SS "Barrier::Barrier ()"

.PP
Конструктор по умолчанию 
.SS "Barrier::Barrier (float x, float y)"

.PP
Конструктор с параметрами 
.SS "Barrier::Barrier (const \fBBarrier\fP & o)"

.PP
Конструктор копирования 
.SS "Barrier::~Barrier ()"

.PP
Деструктор 
.SH "Методы"
.PP 
.SS "bool Barrier::hasPoint (\fBPoint\fP p, \fBGameMap\fP & g)\fC [override]\fP, \fC [virtual]\fP"

.PP
Принадлежит ли точка пространства препятствию 
.PP
\fBАргументы\fP
.RS 4
\fIp\fP точка, которую проверям 
.br
\fIg\fP поле 
.RE
.PP

.PP
Замещает \fBIBarrier\fP\&.
.PP
Переопределяется в \fBBQuadrAngle\fP\&.
.SS "bool Barrier::hasVertex (int v, \fBGameMap\fP & g)\fC [override]\fP, \fC [virtual]\fP"

.PP
Принадлежит ли вершина графа препятствию 
.PP
\fBАргументы\fP
.RS 4
\fIv\fP вершина графа, которую проверям 
.br
\fIg\fP поле 
.RE
.PP

.PP
Замещает \fBIBarrier\fP\&.
.PP
Переопределяется в \fBBQuadrAngle\fP\&.
.SS "int Barrier::init (\fBMyGraph\fP & graph, float step, \fBGameMap\fP & g)\fC [override]\fP, \fC [virtual]\fP"

.PP
Инициализация препятсвия на графе 
.PP
\fBАргументы\fP
.RS 4
\fIgrah\fP граф, на который необходимо наложить препятствие 
.br
\fIstep\fP шаг сетки графа 
.br
\fIg\fP поле 
.RE
.PP

.PP
Замещает \fBIBarrier\fP\&.
.PP
Переопределяется в \fBBQuadrAngle\fP\&.
.SS "bool Barrier::isIntersection (\fBPoint\fP a, \fBPoint\fP b)\fC [override]\fP, \fC [virtual]\fP"

.PP
Проверка на пересечение отрезка и препятствия 
.PP
\fBАргументы\fP
.RS 4
\fIa\fP координаты начала отрезка 
.br
\fIb\fP координаты конеца отрезка 
.RE
.PP

.PP
Замещает \fBIBarrier\fP\&.
.PP
Переопределяется в \fBBQuadrAngle\fP\&.
.SS "void Barrier::print (\fBGameMap\fP & g)\fC [override]\fP, \fC [virtual]\fP"

.PP
Печать препятствия в консоль 
.PP
Замещает \fBIBarrier\fP\&.
.PP
Переопределяется в \fBBQuadrAngle\fP\&.
.SS "void Barrier::printToFile (ofstream & out)\fC [override]\fP, \fC [virtual]\fP"

.PP
Печать препятствия в файл 
.PP
Замещает \fBIBarrier\fP\&.
.PP
Переопределяется в \fBBQuadrAngle\fP\&.
.SH "Документация по друзьям класса и функциям, относящимся к классу"
.PP 
.SS "ofstream& operator<< (ofstream & out, const \fBBarrier\fP & barrier)\fC [friend]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
