.TH "barrier.cpp" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
barrier.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'barrier\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBSmoother\fP"
.br
.RI "Класс сглаживания пути "
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "ofstream & \fBoperator<<\fP (ofstream &out, const \fBBarrier\fP &barrier)"
.br
.ti -1c
.RI "ofstream & \fBoperator<<\fP (ofstream &out, const \fBBQuadrAngle\fP &barrier)"
.br
.ti -1c
.RI "int \fBarea\fP (\fBPoint\fP a, \fBPoint\fP b, \fBPoint\fP c)"
.br
.ti -1c
.RI "bool \fBintersect_1\fP (int a, int b, int c, int d)"
.br
.in -1c
.SH "Функции"
.PP 
.SS "int area (\fBPoint\fP a, \fBPoint\fP b, \fBPoint\fP c)\fC [inline]\fP"

.SS "bool intersect_1 (int a, int b, int c, int d)\fC [inline]\fP"

.SS "ofstream& operator<< (ofstream & out, const \fBBarrier\fP & barrier)"

.SS "ofstream& operator<< (ofstream & out, const \fBBQuadrAngle\fP & barrier)"

.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
