.TH "diagonal_heuristic< Graph, CostType, LocMap >" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diagonal_heuristic< Graph, CostType, LocMap >
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:astar_heuristic< Graph, CostType >\&.
.SS "Открытые типы"

.in +1c
.ti -1c
.RI "typedef graph_traits< Graph >::\fBvertex_descriptor\fP \fBVertex\fP"
.br
.in -1c
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBdiagonal_heuristic\fP (LocMap l, \fBVertex\fP goal)"
.br
.ti -1c
.RI "CostType \fBoperator()\fP (\fBVertex\fP u)"
.br
.in -1c
.SH "Определения типов"
.PP 
.SS "template<class Graph , class CostType , class LocMap > typedef graph_traits<Graph>::\fBvertex_descriptor\fP \fBdiagonal_heuristic\fP< Graph, CostType, LocMap >::\fBVertex\fP"

.SH "Конструктор(ы)"
.PP 
.SS "template<class Graph , class CostType , class LocMap > \fBdiagonal_heuristic\fP< Graph, CostType, LocMap >::\fBdiagonal_heuristic\fP (LocMap l, \fBVertex\fP goal)\fC [inline]\fP"

.SH "Методы"
.PP 
.SS "template<class Graph , class CostType , class LocMap > CostType \fBdiagonal_heuristic\fP< Graph, CostType, LocMap >::operator() (\fBVertex\fP u)\fC [inline]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
