.TH "DMQuadrangle" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMQuadrangle \- Класс прямоугольной матрицы расстояний  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <locationmap\&.h>\fP
.PP
Базовые классы:\fBDistanceMatrix\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBDMQuadrangle\fP ()"
.br
.RI "Конструктор по умолчанию "
.ti -1c
.RI "\fBDMQuadrangle\fP (int width, int height, int center, float step)"
.br
.RI "Конструктор с параметрами "
.ti -1c
.RI "\fBDMQuadrangle\fP (const \fBDMQuadrangle\fP &o)"
.br
.RI "Конструктор копирования "
.ti -1c
.RI "void \fBinit\fP () override"
.br
.RI "Инициализация матрицы расстояний "
.ti -1c
.RI "void \fBprint\fP () override"
.br
.RI "Печать матрицы расстояний в консоль "
.ti -1c
.RI "\fB~DMQuadrangle\fP () override"
.br
.in -1c
.SS "Дополнительные унаследованные члены"
.SH "Подробное описание"
.PP 
Класс прямоугольной матрицы расстояний 

Матрица создается на базе вектора точек (x, y)\&. 
.br
Значение \fBwidth\fP задает количество элементов матрицы по ширине\&. 
.br
Значение \fBheight\fP задает количетво элементов матрицы по высоте\&. 
.br
Значение \fBstep\fP(шаг) отвечает за расстояние от одной точки до другой\&. 
.br
Значение \fBcenter\fP задает номер элемента матрицы, который будет считаться точкой отсчета\&. 
.br
На рисунке представлена схема прямоугольной матрицы расстояний, с точкой отсчета в элементе под номером 12\&. 
.PP
 
.SH "Конструктор(ы)"
.PP 
.SS "DMQuadrangle::DMQuadrangle ()"

.PP
Конструктор по умолчанию 
.SS "DMQuadrangle::DMQuadrangle (int width, int height, int center, float step)"

.PP
Конструктор с параметрами 
.SS "DMQuadrangle::DMQuadrangle (const \fBDMQuadrangle\fP & o)"

.PP
Конструктор копирования 
.SS "DMQuadrangle::~DMQuadrangle ()\fC [override]\fP"

.SH "Методы"
.PP 
.SS "void DMQuadrangle::init ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Инициализация матрицы расстояний 
.PP
Переопределяет метод предка \fBDistanceMatrix\fP\&.
.SS "void DMQuadrangle::print ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Печать матрицы расстояний в консоль 
.PP
Переопределяет метод предка \fBDistanceMatrix\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
