.TH "gamemap.h" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gamemap.h
.SH SYNOPSIS
.br
.PP
\fC#include 'locationmap\&.h'\fP
.br
\fC#include 'mygraph\&.h'\fP
.br
\fC#include 'barrier\&.h'\fP
.br
\fC#include 'point\&.h'\fP
.br
\fC#include 'mylog\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBGameMap\fP"
.br
.RI "Класс игрового поля "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
