.TH "GameMap" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameMap \- Класс игрового поля  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gamemap\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBGameMap\fP ()"
.br
.RI "Конструктор по умолчанию "
.ti -1c
.RI "\fBGameMap\fP (float \fBwidth_coord\fP, float \fBheight_coord\fP, float \fBstep\fP, int \fBcenter\fP, float \fBwidth_auto\fP, float \fBheight_auto\fP, \fBPoint\fP goal_p, bool \fBisSmoothing\fP)"
.br
.RI "Конструктор с параметрами "
.ti -1c
.RI "list< \fBPoint\fP > \fBcreate_msg\fP (const \fBDistanceMatrix\fP &locations, list< \fBvertex_descriptor\fP > &shortest_path)"
.br
.RI "Формирование сообщения под отправку "
.ti -1c
.RI "void \fBprint_game_map\fP ()"
.br
.RI "Печать игрового поля в консоль "
.ti -1c
.RI "void \fBprint_vertex_map\fP ()"
.br
.RI "Печать вершин игрового поля в консоль "
.ti -1c
.RI "void \fBprint_way\fP (const \fBDistanceMatrix\fP *\fBdistance\fP, const list< \fBvertex_descriptor\fP > &shortest_path)"
.br
.RI "Печать пути "
.ti -1c
.RI "int \fBGetJ\fP (float i)"
.br
.ti -1c
.RI "int \fBGetI\fP (float j)"
.br
.ti -1c
.RI "void \fBinit\fP (\fBIDistanceMatrix\fP &\fBdistance\fP, \fBIGraph\fP &\fBgraph\fP)"
.br
.ti -1c
.RI "void \fBdoo\fP (const int DEBUG_OUTPUT)"
.br
.ti -1c
.RI "void \fBprintToFile\fP (ofstream &out)"
.br
.RI "Печать в файл "
.ti -1c
.RI "\fB~GameMap\fP ()"
.br
.RI "Деструктор "
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "float \fBstep\fP"
.br
.RI "Шаг вершин графа "
.ti -1c
.RI "float \fBwidth_coord\fP"
.br
.RI "Ширина покрытия сетки графа "
.ti -1c
.RI "float \fBheight_coord\fP"
.br
.RI "Высота покрытия сетки графа "
.ti -1c
.RI "int \fBnum_vertices_width\fP"
.br
.RI "Количество вершин графа по ширине "
.ti -1c
.RI "int \fBnum_vertices_height\fP"
.br
.RI "Количество вершин графа по высоте "
.ti -1c
.RI "int \fBcenter\fP"
.br
.RI "Начало отсчета системы координат (наша машина) "
.ti -1c
.RI "\fBPoint\fP \fBgoal_point\fP"
.br
.RI "Точка конечного маршрута "
.ti -1c
.RI "\fBvertex_descriptor\fP \fBstart\fP"
.br
.RI "Вершина графа откуда стартует авто "
.ti -1c
.RI "int \fBgoal\fP"
.br
.RI "Вершина графа куда едем "
.ti -1c
.RI "float \fBwidth_auto\fP"
.br
.RI "Ширина авто "
.ti -1c
.RI "float \fBheight_auto\fP"
.br
.RI "Высота авто "
.ti -1c
.RI "\fBMyGraph\fP * \fBgraph\fP"
.br
.RI "Навигационный граф "
.ti -1c
.RI "\fBDistanceMatrix\fP * \fBdistance\fP"
.br
.RI "Матрица расстояний навигационного графа "
.ti -1c
.RI "list< \fBBarrier\fP * > \fBbarriers\fP"
.br
.RI "Список препятствий "
.ti -1c
.RI "list< \fBPoint\fP > \fBshort_path\fP"
.br
.RI "Кратчайший путь "
.ti -1c
.RI "bool \fBisSmoothing\fP"
.br
.RI "Конструктор с параметрами "
.in -1c
.SH "Подробное описание"
.PP 
Класс игрового поля 

Игровое поле представляет из себя матрицу расстояний (\fBdistance\fP) наложенную на граф (\fBgraph\fP), см\&. рис\&. ниже 
.PP
 
.SH "Конструктор(ы)"
.PP 
.SS "GameMap::GameMap ()"

.PP
Конструктор по умолчанию 
.SS "GameMap::GameMap (float width_coord, float height_coord, float step, int center, float width_auto, float height_auto, \fBPoint\fP goal_p, bool isSmoothing)"

.PP
Конструктор с параметрами 
.SS "GameMap::~GameMap ()"

.PP
Деструктор 
.SH "Методы"
.PP 
.SS "list< \fBPoint\fP > GameMap::create_msg (const \fBDistanceMatrix\fP & locations, list< \fBvertex_descriptor\fP > & shortest_path)"

.PP
Формирование сообщения под отправку 
.SS "void GameMap::doo (const int DEBUG_OUTPUT)"

.SS "int GameMap::GetI (float j)"

.SS "int GameMap::GetJ (float i)"

.SS "void GameMap::init (\fBIDistanceMatrix\fP & distance, \fBIGraph\fP & graph)"

.SS "void GameMap::print_game_map ()"

.PP
Печать игрового поля в консоль 
.SS "void GameMap::print_vertex_map ()"

.PP
Печать вершин игрового поля в консоль 
.SS "void GameMap::print_way (const \fBDistanceMatrix\fP * distance, const list< \fBvertex_descriptor\fP > & shortest_path)"

.PP
Печать пути 
.SS "void GameMap::printToFile (ofstream & out)"

.PP
Печать в файл 
.SH "Данные класса"
.PP 
.SS "list<\fBBarrier\fP*> GameMap::barriers"

.PP
Список препятствий 
.SS "int GameMap::center"

.PP
Начало отсчета системы координат (наша машина) 
.SS "\fBDistanceMatrix\fP* GameMap::distance"

.PP
Матрица расстояний навигационного графа 
.SS "int GameMap::goal"

.PP
Вершина графа куда едем 
.SS "\fBPoint\fP GameMap::goal_point"

.PP
Точка конечного маршрута 
.SS "\fBMyGraph\fP* GameMap::graph"

.PP
Навигационный граф 
.SS "float GameMap::height_auto"

.PP
Высота авто 
.SS "float GameMap::height_coord"

.PP
Высота покрытия сетки графа 
.SS "bool GameMap::isSmoothing"

.PP
Конструктор с параметрами 
.SS "int GameMap::num_vertices_height"

.PP
Количество вершин графа по высоте 
.SS "int GameMap::num_vertices_width"

.PP
Количество вершин графа по ширине 
.SS "list<\fBPoint\fP> GameMap::short_path"

.PP
Кратчайший путь 
.SS "\fBvertex_descriptor\fP GameMap::start"

.PP
Вершина графа откуда стартует авто 
.SS "float GameMap::step"

.PP
Шаг вершин графа 
.SS "float GameMap::width_auto"

.PP
Ширина авто 
.SS "float GameMap::width_coord"

.PP
Ширина покрытия сетки графа 

.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
