.TH "gamemap.cpp" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gamemap.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'gamemap\&.h'\fP
.br
\fC#include <boost/graph/adjacency_list\&.hpp>\fP
.br
\fC#include <QtDebug>\fP
.br
\fC#include <QTime>\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
