.TH "IBarrier" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IBarrier \- Интерфейс препятствия  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <barrier\&.h>\fP
.PP
Производные классы:\fBBarrier\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "virtual \fB~IBarrier\fP ()=0"
.br
.RI "Виртуальный деструктор "
.ti -1c
.RI "virtual int \fBinit\fP (\fBMyGraph\fP &graph, float step, \fBGameMap\fP &g)=0"
.br
.RI "Инициализация препятсвия на графе "
.ti -1c
.RI "virtual void \fBprint\fP (\fBGameMap\fP &g)=0"
.br
.RI "Печать препятствия в консоль "
.ti -1c
.RI "virtual void \fBprintToFile\fP (ofstream &out)=0"
.br
.RI "Печать препятствия в файл "
.ti -1c
.RI "virtual bool \fBhasPoint\fP (\fBPoint\fP p, \fBGameMap\fP &g)=0"
.br
.RI "Принадлежит ли точка пространства препятствию "
.ti -1c
.RI "virtual bool \fBhasVertex\fP (int v, \fBGameMap\fP &g)=0"
.br
.RI "Принадлежит ли вершина графа препятствию "
.ti -1c
.RI "virtual bool \fBisIntersection\fP (\fBPoint\fP a, \fBPoint\fP b)=0"
.br
.RI "Проверка на пересечение отрезка и препятствия "
.in -1c
.SH "Подробное описание"
.PP 
Интерфейс препятствия 
.SH "Конструктор(ы)"
.PP 
.SS "IBarrier::~IBarrier ()\fC [pure virtual]\fP"

.PP
Виртуальный деструктор 
.SH "Методы"
.PP 
.SS "virtual bool IBarrier::hasPoint (\fBPoint\fP p, \fBGameMap\fP & g)\fC [pure virtual]\fP"

.PP
Принадлежит ли точка пространства препятствию 
.PP
\fBАргументы\fP
.RS 4
\fIp\fP точка, которую проверям 
.br
\fIg\fP поле 
.RE
.PP

.PP
Замещается в \fBBQuadrAngle\fP и \fBBarrier\fP\&.
.SS "virtual bool IBarrier::hasVertex (int v, \fBGameMap\fP & g)\fC [pure virtual]\fP"

.PP
Принадлежит ли вершина графа препятствию 
.PP
\fBАргументы\fP
.RS 4
\fIv\fP вершина графа, которую проверям 
.br
\fIg\fP поле 
.RE
.PP

.PP
Замещается в \fBBQuadrAngle\fP и \fBBarrier\fP\&.
.SS "virtual int IBarrier::init (\fBMyGraph\fP & graph, float step, \fBGameMap\fP & g)\fC [pure virtual]\fP"

.PP
Инициализация препятсвия на графе 
.PP
\fBАргументы\fP
.RS 4
\fIgrah\fP граф, на который необходимо наложить препятствие 
.br
\fIstep\fP шаг сетки графа 
.br
\fIg\fP поле 
.RE
.PP

.PP
Замещается в \fBBQuadrAngle\fP и \fBBarrier\fP\&.
.SS "virtual bool IBarrier::isIntersection (\fBPoint\fP a, \fBPoint\fP b)\fC [pure virtual]\fP"

.PP
Проверка на пересечение отрезка и препятствия 
.PP
\fBАргументы\fP
.RS 4
\fIa\fP координаты начала отрезка 
.br
\fIb\fP координаты конеца отрезка 
.RE
.PP

.PP
Замещается в \fBBQuadrAngle\fP и \fBBarrier\fP\&.
.SS "virtual void IBarrier::print (\fBGameMap\fP & g)\fC [pure virtual]\fP"

.PP
Печать препятствия в консоль 
.PP
Замещается в \fBBQuadrAngle\fP и \fBBarrier\fP\&.
.SS "virtual void IBarrier::printToFile (ofstream & out)\fC [pure virtual]\fP"

.PP
Печать препятствия в файл 
.PP
Замещается в \fBBQuadrAngle\fP и \fBBarrier\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
