.TH "IDistanceMatrix" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IDistanceMatrix \- Интерфейс матрицы расстояний  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <locationmap\&.h>\fP
.PP
Производные классы:\fBDistanceMatrix\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP ()=0"
.br
.RI "Инициализация матрицы расстояний "
.ti -1c
.RI "virtual void \fBprint\fP ()=0"
.br
.RI "Печать матрицы расстояний в консоль "
.ti -1c
.RI "virtual \fB~IDistanceMatrix\fP ()=0"
.br
.RI "Виртуальный деструктор "
.in -1c
.SH "Подробное описание"
.PP 
Интерфейс матрицы расстояний 
.SH "Конструктор(ы)"
.PP 
.SS "IDistanceMatrix::~IDistanceMatrix ()\fC [pure virtual]\fP"

.PP
Виртуальный деструктор 
.SH "Методы"
.PP 
.SS "virtual void IDistanceMatrix::init ()\fC [pure virtual]\fP"

.PP
Инициализация матрицы расстояний 
.PP
Замещается в \fBDMQuadrangle\fP и \fBDistanceMatrix\fP\&.
.SS "virtual void IDistanceMatrix::print ()\fC [pure virtual]\fP"

.PP
Печать матрицы расстояний в консоль 
.PP
Замещается в \fBDMQuadrangle\fP и \fBDistanceMatrix\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
