.TH "locationmap.h" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
locationmap.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'point\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBIDistanceMatrix\fP"
.br
.RI "Интерфейс матрицы расстояний "
.ti -1c
.RI "class \fBDistanceMatrix\fP"
.br
.RI "Базовый класс матрицы расстояний "
.ti -1c
.RI "class \fBDMQuadrangle\fP"
.br
.RI "Класс прямоугольной матрицы расстояний "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
