.TH "main.cpp" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QCoreApplication>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include 'mytcpsocket\&.h'\fP
.br
\fC#include 'settings\&.h'\fP
.br
\fC#include 'myexception\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Функции"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
