.TH "myexception.h" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myexception.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBMyException\fP"
.br
.RI "Класс исключений "
.in -1c
.SS "Макросы"

.in +1c
.ti -1c
.RI "#define \fBPathNotFound\fP   0"
.br
.RI "Путь не найден исключений "
.ti -1c
.RI "#define \fBConfigNotFound\fP   \-1"
.br
.RI "Конфигурационный файл не найден "
.ti -1c
.RI "#define \fBDataPackageError\fP   \-3"
.br
.RI "Неправильный формат пакета с данными "
.in -1c
.SH "Макросы"
.PP 
.SS "#define ConfigNotFound   \-1"

.PP
Конфигурационный файл не найден 
.SS "#define DataPackageError   \-3"

.PP
Неправильный формат пакета с данными 
.SS "#define PathNotFound   0"

.PP
Путь не найден исключений 
.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
