.TH "MyException" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyException \- Класс исключений  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <myexception\&.h>\fP
.PP
Базовые классы:exception\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMyException\fP (const char *msg)"
.br
.ti -1c
.RI "\fBMyException\fP (int ErrorCode)"
.br
.ti -1c
.RI "\fBMyException\fP (const char *msg, int ErrorCode)"
.br
.ti -1c
.RI "\fB~MyException\fP ()"
.br
.ti -1c
.RI "int \fBGetErrorCode\fP ()"
.br
.ti -1c
.RI "void \fBSetErrorCode\fP (int ErrorCode)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const _GLIBCXX_TXN_SAFE_DYN _GLIBCXX_NOTHROW override"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс исключений 
.SH "Конструктор(ы)"
.PP 
.SS "MyException::MyException (const char * msg)"

.SS "MyException::MyException (int ErrorCode)"

.SS "MyException::MyException (const char * msg, int ErrorCode)"

.SS "MyException::~MyException ()"

.SH "Методы"
.PP 
.SS "int MyException::GetErrorCode ()"

.SS "void MyException::SetErrorCode (int ErrorCode)"

.SS "const char * MyException::what () const\fC [override]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
