.TH "mygraph.h" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mygraph.h
.SH SYNOPSIS
.br
.PP
\fC#include <boost/graph/adjacency_list\&.hpp>\fP
.br
\fC#include <boost/graph/graphviz\&.hpp>\fP
.br
\fC#include <boost/graph/astar_search\&.hpp>\fP
.br
\fC#include 'locationmap\&.h'\fP
.br
\fC#include 'point\&.h'\fP
.br
\fC#include 'myexception\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBIGraph\fP"
.br
.RI "Интерфейс графа "
.ti -1c
.RI "class \fBMyGraph\fP"
.br
.RI "Класс для построения неориентированного прямоугольного графа "
.in -1c
.SS "Определения типов"

.in +1c
.ti -1c
.RI "typedef boost::property< boost::edge_weight_t, float > \fBweight\fP"
.br
.RI "Вес ребра "
.ti -1c
.RI "typedef adjacency_list< vecS, vecS, undirectedS, boost::no_property, \fBweight\fP > \fBmy_graph\fP"
.br
.RI "Граф (список смежности) "
.ti -1c
.RI "typedef boost::graph_traits< \fBmy_graph\fP >::\fBedge_iterator\fP \fBedge_iterator\fP"
.br
.RI "Итератор дуг "
.ti -1c
.RI "typedef boost::graph_traits< \fBmy_graph\fP >::\fBvertex_iterator\fP \fBvertex_iterator\fP"
.br
.RI "Итератор вершин "
.ti -1c
.RI "typedef boost::property_map< \fBmy_graph\fP, boost::edge_weight_t >::type \fBWeight_Map\fP"
.br
.RI "Карта весов рёбер "
.ti -1c
.RI "typedef std::pair< \fBedge_iterator\fP, \fBedge_iterator\fP > \fBedgePair\fP"
.br
.RI "Пара итераторов для ребра "
.ti -1c
.RI "typedef std::pair< \fBvertex_iterator\fP, \fBvertex_iterator\fP > \fBvertexPair\fP"
.br
.RI "Пара итераторов для вершины "
.ti -1c
.RI "typedef graph_traits< \fBmy_graph\fP >::\fBvertex_descriptor\fP \fBvertex_descriptor\fP"
.br
.RI "Дескриптор вершин "
.ti -1c
.RI "typedef graph_traits< \fBmy_graph\fP >::\fBedge_descriptor\fP \fBedge_descriptor\fP"
.br
.RI "Дескриптор рёбер "
.in -1c
.SH "Типы"
.PP 
.SS "typedef graph_traits<\fBmy_graph\fP>::\fBedge_descriptor\fP \fBedge_descriptor\fP"

.PP
Дескриптор рёбер 
.SS "typedef boost::graph_traits<\fBmy_graph\fP>::\fBedge_iterator\fP \fBedge_iterator\fP"

.PP
Итератор дуг 
.SS "typedef std::pair<\fBedge_iterator\fP, \fBedge_iterator\fP> \fBedgePair\fP"

.PP
Пара итераторов для ребра 
.SS "typedef adjacency_list<vecS, vecS, undirectedS, boost::no_property, \fBweight\fP> \fBmy_graph\fP"

.PP
Граф (список смежности) 
.SS "typedef graph_traits<\fBmy_graph\fP>::\fBvertex_descriptor\fP \fBvertex_descriptor\fP"

.PP
Дескриптор вершин 
.SS "typedef boost::graph_traits<\fBmy_graph\fP>::\fBvertex_iterator\fP \fBvertex_iterator\fP"

.PP
Итератор вершин 
.SS "typedef std::pair<\fBvertex_iterator\fP, \fBvertex_iterator\fP> \fBvertexPair\fP"

.PP
Пара итераторов для вершины 
.SS "typedef boost::property<boost::edge_weight_t, float> \fBweight\fP"

.PP
Вес ребра 
.SS "typedef boost::property_map<\fBmy_graph\fP, boost::edge_weight_t>::type \fBWeight_Map\fP"

.PP
Карта весов рёбер 
.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
