.TH "mylog.cpp" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mylog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mylog\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "template<class T > ofstream & \fBoperator<<\fP (ofstream &out, const T &o)"
.br
.in -1c
.SH "Функции"
.PP 
.SS "template<class T > ofstream& operator<< (ofstream & out, const T & o)"

.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
