.TH "MyTcpSocket" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyTcpSocket
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mytcpsocket\&.h>\fP
.PP
Базовые классы:QObject\&.
.SS "Открытые слоты"

.in +1c
.ti -1c
.RI "void \fBconnected\fP ()"
.br
.ti -1c
.RI "void \fBdisconnected\fP ()"
.br
.ti -1c
.RI "void \fBbytesWritten\fP (qint64 bytes)"
.br
.ti -1c
.RI "void \fBreadyRead\fP ()"
.br
.ti -1c
.RI "void \fBError\fP (QAbstractSocket::SocketError socketError)"
.br
.ti -1c
.RI "void \fBreconnect\fP ()"
.br
.in -1c
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMyTcpSocket\fP (QObject *parent=0)"
.br
.ti -1c
.RI "void \fBdoConnect\fP (const QString &IP, const int PORT, const int DEBUG_OUTPUT, const bool PRINT_LOG, const int RECONNECT_TIME)"
.br
.ti -1c
.RI "\fB~MyTcpSocket\fP ()"
.br
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "MyTcpSocket::MyTcpSocket (QObject * parent = \fC0\fP)\fC [explicit]\fP"

.SS "MyTcpSocket::~MyTcpSocket ()"

.SH "Методы"
.PP 
.SS "void MyTcpSocket::bytesWritten (qint64 bytes)\fC [slot]\fP"

.SS "void MyTcpSocket::connected ()\fC [slot]\fP"

.SS "void MyTcpSocket::disconnected ()\fC [slot]\fP"

.SS "void MyTcpSocket::doConnect (const QString & IP, const int PORT, const int DEBUG_OUTPUT, const bool PRINT_LOG, const int RECONNECT_TIME)"

.SS "void MyTcpSocket::Error (QAbstractSocket::SocketError socketError)\fC [slot]\fP"

.SS "void MyTcpSocket::readyRead ()\fC [slot]\fP"

.SS "void MyTcpSocket::reconnect ()\fC [slot]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
