.TH "mytcpsocket.cpp" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mytcpsocket.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mytcpsocket\&.h'\fP
.br
\fC#include <QDataStream>\fP
.br
\fC#include 'myexception\&.h'\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QTime>\fP
.br
\fC#include <QCoreApplication>\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBdelay\fP (const int RECONNECT_TIME)"
.br
.in -1c
.SH "Функции"
.PP 
.SS "void delay (const int RECONNECT_TIME)"

.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
