.TH "point.cpp" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'point\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "std::ofstream & \fBoperator<<\fP (std::ofstream &out, const \fBPoint\fP &p)"
.br
.in -1c
.SH "Функции"
.PP 
.SS "std::ofstream& operator<< (std::ofstream & out, const \fBPoint\fP & p)"

.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
