.TH "point.h" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point.h
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBPoint\fP"
.br
.RI "Класс точки "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
