.TH "settings.h" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
settings.h
.SH SYNOPSIS
.br
.PP
\fC#include <QVariant>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QMetaEnum>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBSettings\fP"
.br
.ti -1c
.RI "class \fBSettings::ValueRef\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
