.TH "Settings" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Settings
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <settings\&.h>\fP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBValueRef\fP"
.br
.in -1c
.SS "Открытые типы"

.in +1c
.ti -1c
.RI "enum \fBSection\fP { \fBGeneral\fP, \fBNetwork\fP, \fBDebug\fP }"
.br
.ti -1c
.RI "enum \fBKey\fP { \fBIP_SERVER\fP, \fBPORT\fP, \fBDEBUG_OUTPUT\fP, \fBPRINT_LOG\fP, \fBRECONNECT_TIME\fP }"
.br
.in -1c
.SS "Открытые статические члены"

.in +1c
.ti -1c
.RI "static void \fBsetDefaults\fP (const QString &str)"
.br
.ti -1c
.RI "static QVariant \fBget\fP (\fBKey\fP, \fBSection\fP=\fBGeneral\fP)"
.br
.ti -1c
.RI "static \fBValueRef\fP \fBset\fP (\fBKey\fP, \fBSection\fP=\fBGeneral\fP)"
.br
.in -1c
.SH "Перечисления"
.PP 
.SS "enum \fBSettings::Key\fP"

.PP
\fBЭлементы перечислений\fP
.in +1c
.TP
\fB\fIIP_SERVER \fP\fP
.TP
\fB\fIPORT \fP\fP
.TP
\fB\fIDEBUG_OUTPUT \fP\fP
.TP
\fB\fIPRINT_LOG \fP\fP
.TP
\fB\fIRECONNECT_TIME \fP\fP
.SS "enum \fBSettings::Section\fP"

.PP
\fBЭлементы перечислений\fP
.in +1c
.TP
\fB\fIGeneral \fP\fP
.TP
\fB\fINetwork \fP\fP
.TP
\fB\fIDebug \fP\fP
.SH "Методы"
.PP 
.SS "QVariant Settings::get (\fBKey\fP k, \fBSection\fP s = \fC\fBGeneral\fP\fP)\fC [static]\fP"

.SS "\fBSettings::ValueRef\fP Settings::set (\fBKey\fP k, \fBSection\fP s = \fC\fBGeneral\fP\fP)\fC [static]\fP"

.SS "void Settings::setDefaults (const QString & str)\fC [static]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
