.TH "settings.cpp" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
settings.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'settings\&.h'\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QMetaEnum>\fP
.br
\fC#include <QRegExp>\fP
.br
\fC#include <QStringList>\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
