.TH "Settings::ValueRef" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Settings::ValueRef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <settings\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBValueRef\fP (\fBSettings\fP &st, const QString &kp)"
.br
.ti -1c
.RI "\fBValueRef\fP & \fBoperator=\fP (const QVariant &d)"
.br
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "Settings::ValueRef::ValueRef (\fBSettings\fP & st, const QString & kp)\fC [inline]\fP"

.SH "Методы"
.PP 
.SS "\fBSettings::ValueRef\fP & Settings::ValueRef::operator= (const QVariant & d)"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
