.TH "Smoother" 3 "Ср 20 Апр 2022" "Version 1.0" "Блок принятия решений" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Smoother \- Класс сглаживания пути  

.SH SYNOPSIS
.br
.PP
.SS "Открытые статические члены"

.in +1c
.ti -1c
.RI "static list< \fBPoint\fP > \fBPolyclip\fP (list< \fBPoint\fP > pin, \fBPoint\fP segStart, \fBPoint\fP segEnd)"
.br
.ti -1c
.RI "static bool \fBSegmentIntersection\fP (double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс сглаживания пути 
.SH "Методы"
.PP 
.SS "static list<\fBPoint\fP> Smoother::Polyclip (list< \fBPoint\fP > pin, \fBPoint\fP segStart, \fBPoint\fP segEnd)\fC [inline]\fP, \fC [static]\fP"

.SS "static bool Smoother::SegmentIntersection (double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4)\fC [inline]\fP, \fC [static]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Блок принятия решений из исходного текста\&.
